### PR TITLE
Fix migration process to update database

### LINKED ISSUE #73: Clients should eliminate duplicate Crops coming from server
Currently when the server database is destroyed and created again with `npm run migrate`, the clients end up with duplicate Crop documents (this can be fixed by manually removing the local IndexedDB databases). There should be logic in the client to keep only the latest crop document that comes from the server.

### PR DESCRIPTION
**Pull request by petteripitkanen**
Fixes #73 and #67 by fixing the migration process to update the database instead of each time creating a new one from scratch.

### CODE REVIEW

File: cli/cli.js [hunk 1]
```diff
@@ -107,25 +108,41 @@ async function pouchMigrate() {
 
     console.log(await remote.info());
 
-    await remote.destroy();
+    const documents = await remote.allDocs({ include_docs: true });
+    const crops = documents.rows.map(document => document.doc);
+    const binomialNameToCrop = mapCropsByBinomialName(crops);
```
Comment (gljivar) [inline cli/cli.js]: I would suggest in this case to not allow editing of binomial name. As in case of editing binomial name, after rerun of migration this part will create new record with old binomial name so there will be kind of duplicate entry.

Comment (petteripitkanen) [reply cli/cli.js]: I opened #85 for redefining and specifying the migration process.

The migration/initialization process would be somewhat easier to implement if the initial dataset contained IDs, but I prefer to keep `practicalplants.json` database agnostic so in my opinion there shouldn't be IDs in this file (IDs could be removed during #70).
